import {StyleSheet} from 'react-native';
import {normalize} from 'src/utils/utils';

export default StyleSheet.create({
  item: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    position: 'relative',
    width: normalize(160),
    height: normalize(255),
    borderRadius: normalize(4),
    overflow: 'hidden',
  },
  avatarImg: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    width: normalize(160),
    height: normalize(233),
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  nameContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: normalize(5),
    padding: normalize(8),
  },
  nameContent: {
    dispatch: 'flex',
    paddingLeft: normalize(8),
    flexDirection: 'column',
    borderLeftWidth: normalize(4),
    borderColor: '#00C2FF',
  },
  skinName: {
    fontWeight: '600',
    color: '#00F0FF',
    fontSize: normalize(8),
    lineHeight: normalize(12),
    textTransform: 'uppercase',
  },
  name: {
    fontWeight: '700',
    color: '#FFF',
    fontSize: normalize(12),
    lineHeight: normalize(17.5),
    textTransform: 'uppercase',
  },
  releaseContainer: {
    paddingHorizontal: normalize(9),
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dollarContainer: {
    paddingHorizontal: normalize(9),
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: normalize(8),
  },
  releaseText: {
    fontWeight: '600',
    color: '#FFF',
    fontSize: normalize(8),
    lineHeight: normalize(12),
  },
  priceTHC: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: normalize(4),
  },
  thcIcon: {
    width: normalize(10),
    height: normalize(10),
  },
  thcText: {
    color: '#FFE076',
    fontWeight: '600',
    fontSize: normalize(12.36),
    lineHeight: normalize(17),
  },
  dollarPrice: {
    fontWeight: '400',
    fontSize: normalize(9),
    lineHeight: normalize(13),
    color: '#C6C9DC',
    display: 'flex',
    alignSelf: 'flex-end',
  },
  battleText: {
    fontWeight: '400',
    fontSize: normalize(10),
    lineHeight: normalize(14),
    color: '#10FF00',
  },
  infoContainer: {
    width: '100%',
    paddingVertical: normalize(5),
    paddingHorizontal: normalize(8),
    paddingLeft: normalize(21),
    backgroundColor: '#1B1444',
    position: 'relative',
  },
  cornerTag: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    borderTopRightRadius: normalize(8),
    backgroundColor: '#5336D0',
    paddingVertical: normalize(1),
    paddingHorizontal: normalize(12),
  },
  tagText: {
    fontWeight: '500',
    fontSize: normalize(14),
    lineHeight: normalize(22),
  },
});
